name: figma_overlay_clean
description: A desktop overlay tool using Clean Architecture and GetX

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  get: ^4.6.6
  
  # Desktop window management
  window_manager: ^0.3.9
  bitsdojo_window: ^0.1.6 
  
  # File handling
  file_picker: ^8.0.0+1
  path_provider: ^2.1.3
  
  # HTTP for Figma API
  http: ^1.2.1
  dio: ^5.4.3+1

  # Drag and Drop support
  desktop_drop: ^0.4.4
  cross_file: ^0.3.3+8
  
  # Functional Programming
  dartz: ^0.10.1

  #svg 
  flutter_svg: ^2.2.3

  #google fonts 
  google_fonts: ^8.0.1


  #Supabase flutter pacage 
  supabase_flutter: ^2.12.0

  # social authentication pacakage 
  app_links: ^6.0.0  # Handles the deep link (io.supabase.flutter)
  url_launcher: ^6.2.0  # Opens the browser for GitHub login
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/
    - assets/icons/
   


